name: majdoor_frontend
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6  # Update to a version that supports null safety
  shared_preferences: ^2.3.2  # Update to the latest version
  socket_io_client: ^2.0.3+1  # Update to a version that supports null safety
  image_picker: ^1.1.2
  video_player: ^2.9.1
  file_picker: ^8.1.2
  image_size_getter: ^2.1.3
  url_launcher: ^6.1.7
  filter_list: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/first.jpg
    - assets/images/dog.jpg
    - assets/images/

